devenv_dir: "{{ ansible_env.HOME }}/src/{{ zuul.project.canonical_hostname }}/tungstenfabric-tools/dev-env"
test_dir: "{{ ansible_env.HOME }}/src/{{ zuul.project.canonical_hostname }}/tungstenfabric/test"
contrail_version: "{{ packaging.repo_name }}"
devenv_image_name: "{{ contrail_docker_registry }}/dev-env"
devenv_image_tag: "{{ packaging.version.public }}"
tpc_branch: "{{ zuul.branch | match('^R\\d(\\.\\d+)+$') | ternary(zuul.branch, 'master') }}"
