---
- name: Prepare packaging variables
  contrail_packaging:
    zuul: "{{ zuul }}"
    release_type: "{{ release_type }}"
    build_number: "{{ build_number | default('unset_build_number') }}"

- name: Fetch third-party packages
  command: "cd {{ dev_env_basepath }} && docker exec {{ dev_env_container_name }} ./third_party/fetch_packages.py --site-mirror http://{{ zuul_site_mirror_fqdn }}/repository"
  tags:
    - skip_ansible_lint

- name: Get list of makefile targets
  command: "cd {{ dev_env_basepath }} && docker exec {{ dev_env_container_name }}  make -f tools/packages/Makefile list"
  register: rpm_list
  tags:
    - skip_ansible_lint

- name: Check variables used by makefile
  command: "cd {{ dev_env_basepath }} && docker exec {{ dev_env_container_name }}  make -f tools/packages/Makefile info"
  environment:
    BUILDTAG: "{{ build_tag | default(packaging.version.distrib) }}"
    SRCVER: "{{ packaging.version.upstream }}"
    SKUTAG: ocata
    MANIFESTFILE: "{{ dev_env_manifest_file }}"

- name: Install dependencies and build RPMs
  include: make_rpm.yaml
  with_items: "{{ rpm_list.stdout.split(' ') }}"
