---
repos_remove:
    - { name: base, file: CentOS-Base }
    - { name: updates, file: CentOS-Base }
    - { name: extras, file: CentOS-Base }
    - { name: epel, file: epel }
    - { name: epel-source, file: epel }
repos_file: CentOS-Base
repos_baseurl: http://{{ nexus.fqdn }}/repository
repos_add:
    - { name: updates-mirror, repo: centos7-updates, description: CentOS updates mirror }
    - { name: extras-mirror, repo: centos7-extras, description: CentOS extras mirror }
    - { name: base-mirror, repo: centos7-os, description: CentOS base mirror }
use_epel: yes

