---

# use ansible_distribution for better control instead of ansible_os_family
- name: Configure interfaces
  include: "setup_interface_{{ ansible_distribution }}.yaml"
  with_items:
    - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"
  when:
    - hostvars[inventory_hostname]['ansible_' + item]['type'] == 'ether'
    - not 'ipv4' in hostvars[inventory_hostname]['ansible_' + item]

- name: Reload ansible facts
  setup:
