---

- name: include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yaml"
    - "{{ ansible_os_family | lower }}.yaml"
    - "default.yaml"

- when:
    - cloud_orchestrator == 'openstack'
    - ansible_distribution == 'RedHat'
  block:
    - name: include OpenStack-specific repos
      include_vars: "{{ ansible_distribution | lower }}_openstack_{{ openstack_version }}.yaml"

    - name: add OpenStack repos to repos_add
      set_fact:
        repos_add: "{{ repos_add }} + {{ openstack_repos_add }}"

- when:
    - cloud_orchestrator == 'kubernetes'
    - ansible_distribution == 'RedHat'
  block:
    - name: include OpenShift-specific repos
      include_vars: '{{ ansible_distribution | lower }}_openshift_{{ openshift_version }}.yaml'

    - name: add OpenShift repos to repos_add
      set_fact:
        repos_add: '{{ repos_add }} + {{ openshift_repos_add }}'

- name: prepare centos
  become: yes
  become_user: root
  when: 'ansible_os_family == "RedHat"'
  block:
    - name: disable subscription-manager on RHEL
      command: subscription-manager config --rhsm.manage_repos=0
      when: 'ansible_distribution == "RedHat"'
    - name: remove the upstream yum repos
      yum_repository:
        name: "{{ item.name }}"
        file: "{{ item.file }}"
        state: absent
      with_items: "{{ repos_remove }}"
    - name: prepare local base yum mirror repo file
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        file: "{{ repos_file }}"
        baseurl: "{{ repos_baseurl }}/{{ item.repo }}"
        enabled: yes
        gpgcheck: no
      with_items: "{{ repos_add }}"
    - name: prepare epel mirror repo file
      yum_repository:
        name: epel-mirror
        description: CentOS epel mirror
        file: epel
        baseurl: "{{ repos_baseurl }}/epel"
        enabled: "{{ use_epel }}"
        gpgcheck: no
    - name: prepare docker mirror repo file
      yum_repository:
        name: docker-ce-stable-mirror
        description: Docker CE Stable mirror
        file: docker-ce
        baseurl: "{{ repos_baseurl }}/docker-ce-stable"
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
    - name: prepare third party source cache yum Nexus repo (depends on branch)
      yum_repository:
        name: tpc-source
        description: Contrail third-party source dependencies
        file: tpc-source
        baseurl: "{{ repos_baseurl }}/{{ nexus.repos.yum_tpc_source }}/{{ tpc_branch }}/"
        enabled: yes
        gpgcheck: no
    - name: prepare third party binary cache yum Nexus repo (doesn't depend on branch)
      yum_repository:
        name: tpc-binary
        description: Contrail third-party binary dependencies
        file: tpc-binary
        baseurl: "{{ repos_baseurl }}/{{ nexus.repos.yum_tpc_binary }}/"
        enabled: yes
        gpgcheck: no
